### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by ukBaz**
Move to Bleak BLE Library
Move to using `argparse` from Python standard library
Move to returning Python objects rather than dictionaries
Move to using `EnumInt` for enumerated values
Move to using csv file type for history file
Create entry point tool `aranetctl` for command line usage
Add some unit tests
update setup.py with dependencies

### CODE REVIEW

**Review by Anrijs — APPROVED** [review]

**Comment by Anrijs** [comment]
Merged and uploaded to pip as version 2.0.0

**Comment by ukBaz** [comment]
Excellent!

I've tested it on Windows and Linux. Would be good if someone can test on macOS

**Comment by Anrijs** [comment]
For some reason, I can't pair aranet to M1 mac. Seems like macos issue.

**Comment by ukBaz** [comment]
I don't have a mac to test this with. 

According to the `Bleak` documentation, on macOS it finds other devices via UUIDs rather than Bluetooth address:
https://bleak.readthedocs.io/en/latest/backends/macos.html#specific-features-for-the-macos-backend

There is a Bleak issue about extra permissions need to be set:
https://github.com/hbldh/bleak/issues/284

Is it worth opening an issue where we can record error messages and what has been attempted?

**Comment by Anrijs** [comment]
Pairing issues are not related to `bleak`. This seems to be macos monterey issue: https://developer.apple.com/forums/thread/694146

**Pull request merged**
