### PR TITLE
Visual Studio IDE Support

### PR DESCRIPTION
**Pull request by Matthew1471**
- Added .gitignore to ignore build, Python cache, Visual Studio and Windows artifacts.
- Added Visual Studio solution file and project file to aid with development.

### CODE REVIEW

**Comment by Anrijs** [comment]
I'm not using Visual Studio IDE and project files could become outdated.

**Comment by Matthew1471** [comment]
I'm happy to maintain it.. it does make it hard for me to dev if I can't open it in my IDE easily (https://stackoverflow.com/questions/3403697/should-ide-project-files-be-put-under-source-control) and will have no effect on anyone else's IDE choice... you could add your IDE's project files  (excluding artefacts) too?

Otherwise can you add it (and the .vs autogen'd rubbish) to .gitignore if you definitely don't want them in so I can keep them in my working copy without having to stash changes all the time?

**Comment by ukBaz** [comment]
git has the option to define files to be ignored outside of the primary `.gitignore` file. There is more information at the following link under _Personal Git ignore rules_ and _Global Git ignore rules_

https://www.atlassian.com/git/tutorials/saving-changes/gitignore#personal-git-ignore-rules

These allow users to not accidentally commit their IDE configs without cluttering up the repo `.gitignore`

**Comment by Matthew1471** [comment]
> git has the option to define files to be ignored outside of the primary `.gitignore` file. There is more information at the following link under _Personal Git ignore rules_ and _Global Git ignore rules_
> 
> 
> 
> https://www.atlassian.com/git/tutorials/saving-changes/gitignore#personal-git-ignore-rules
> 
> 
> 
> These allow users to not accidentally commit their IDE configs without cluttering up the repo `.gitignore` 

Will look into that.. thanks 🙂

**Pull request closed without merging**
