### PR TITLE
PyLint

### PR DESCRIPTION
**Pull request by Matthew1471**
- Removed trailing commas from some print statements.
- Specified encoding on file operations.
- Converted some formatted strings to f-strings as this project uses f-strings.
- Marked "addr" as unused in found.items() to show it's not used.
- Color and Status are 2 different things. There is no BLUE color (?) and added missing YELLOW.
- "status_t" and "status_h" was confusing.. refactored to status_temperature and status_humidity.
- Removed erroneous f-string.
- **Optimised _decode_status_flags logic.. but don't have an Aranet2 device to test.**
- Optimised _get_b to be more readable.
- Refactored "tru" and "fal" to "true_condition" and "false_condition" for readability.
- Optimised if start < 1 by using max statement.
- "value" was not used but assigned when reading history.
- Removed superfluous else.
- Fixed comment typo.
- Removed superfluous spaces.
- Removed superfluous parenthesis.
- Removed unused imports.
- Fixed imports not following PEP8 standards
- Fixed incorrect indentation.
- Fixed duplicate function declaration in test_values and fixed test case.
- Fixed string in code being created but not being printed.
- Fixed MQTT example readme listing the wrong syntax.
- Fixed spacing in scanner_simple.py
- "csvfile" wasn't following PEP8, refactored to "csv_file".
- "f" and "fh" was used for non csv files, refactored to "file".
- Specified file param keywords, "r" and "w" might not be as friendly for first time developers.
- Using keywords for requests.post.
- Added an arbitrary 5 minutes timeout to requests.post instead of an indefinite hang.
- Separated multiple statements on single line as per pylint recommendation.
- Fixed some comment capitalisation.
- Commented out an unused field (i in influx).
- Cleaned MQTT import.
- Defined default encoding in test_csv.
- Project used a combination of single and double quotes (sometimes on the same line). PEP8 recommends sticking to one. Project used more double quotes than single quotes, have standardised on that.
- Added mode="r" to import.py.
- Removed trailing commas.

### CODE REVIEW

**Comment by Matthew1471** [comment]
Hope this helps 😊.. I'm adopting a dog tomorrow so I may take a little longer to reply if you need me for anything

**Comment by Anrijs** [comment]
"BLUE" status was for Aranet2, when temperature or humidity is below low threshold. That's how it was displayed in app.

**Comment by Matthew1471** [comment]
> "BLUE" status was for Aranet2, when temperature or humidity is below low threshold. That's how it was displayed in app.

Oh that makes sense! Status 1 = Under.. so Blue = Cold. Status 3 = Dash.. when is that used?

I need to buy an Aranet 2, Radon and Radiation so I can test this better but there's a stock shortage in the UK.

I'll split the classes into separate files.. but just wanted to check if there was a reason why you didn't want to do that before
I do?

**Comment by Anrijs** [comment]
3 might just be reserved/unused value.
There isn't any specific reason why everything is in one file.

**Pull request merged**
